plugins {
    id 'com.android.library'
}

android {
    namespace 'com.partitionsoft.bookshelf.data'
    compileSdk 35

    defaultConfig {
        minSdk 24
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':domain')
    implementation 'androidx.datastore:datastore-preferences:1.1.7'
    api 'com.android.billingclient:billing-ktx:9.1.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.1'
}
